language: cpp

sudo: enabled
dist: trusty


env: 
  - CUDA=8.0.61-1


compiler:
  - clang
  #- gcc
  
before_install:
    - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_${CUDA}_amd64.deb
    - sudo dpkg -i cuda-repo-ubuntu1404_${CUDA}_amd64.deb
    - sudo apt-get update -qq
    - CUDA_APT=${CUDA:0:3}
    - CUDA_APT=${CUDA_APT/./-}
    #- sudo apt-get install -y cuda-drivers cuda-core-${CUDA_APT} cuda-cudart-dev-${CUDA_APT} cuda-cufft-dev-${CUDA_APT}
    - sudo apt-get install cuda
    - sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev
    - sudo apt-get clean
    - CUDA_HOME=/usr/local/cuda-${CUDA:0:3}
    - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
    - PATH=${CUDA_HOME}/bin:${PATH} 
    - wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip
    - unzip ninja-linux.zip
    - wget https://cmake.org/files/v3.9/cmake-3.9.0-Linux-x86_64.sh
    - sh cmake-3.9.0-Linux-x86_64.sh --prefix=${HOME} --skip-license
    - pwd
    - PATH=${PATH}:${PWD}

before_script:

    - mkdir build
    - cd build
    - cmake .. -GNinja -DBUILD_TYPE=STRICT -DQUDA_MPI=ON -DCMAKE_CXX_CLANG_TIDY:STRING="clang-tidy;-checks=*,readability-*,modernize-*" -DQUDA_GPU_ARCH=compute_60

# we build only quda_cpp here
script: ninja -k6 quda_cpp
